# Generated by Django 2.1.3 on 2018-11-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('facultad', models.CharField(max_length=60)),
                ('anios', models.IntegerField()),
                ('profesion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Asesor')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_aprobado', models.DateField()),
                ('descripcion', models.CharField(max_length=120)),
                ('cantidad_integrantes', models.IntegerField()),
                ('nombre_integrantes', models.CharField(max_length=250)),
                ('carreras', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='asesoria',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Proyecto'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='proyectos',
            field=models.ManyToManyField(through='medicamentos.Asesoria', to='medicamentos.Proyecto'),
        ),
    ]
